### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by anselal** [atulmishra-one/dairy_manager#1]
I get an error when trying to install the requirements in arch linux. I cannot install mysql-connector-python, mysql-utilities, oneconf...
I get messages like "Could not find a version that satisfies the requirement oneconf==0.3.7 .. No matching idstibution found for oneconf==0.3.7"

**Comment by atulmishra-one** [comment]
The requirements.txt is for the base system Python, not any virtual environment.

**Comment by atulmishra-one** [comment]
I'll be creating this project with virtual env . for now this issue can be fixed by manually installing the dependencies

**Comment by anselal** [comment]
That is the point of the requirements file, it should work with `virtualenv`. I tried to manually install the requirements but still got the same problems

**Comment by atulmishra-one** [comment]
I'll soon provide a fix to this.  can you do system wide installation by creating a new system user. don't run requirements.txt

**Comment by anselal** [comment]
There is no need to create a new system user to do this. I am working on a Linux system, and system wide, means for all users. I will try it, although there is no meaning in this, and give you feedback.

**Comment by atulmishra-one** [comment]
Thanks for the feedback. Appreciated

**Comment by anselal** [comment]
I still get the same error. This issue is not resolved

**Comment by atulmishra-one** [comment]
Created project with virtual env.

**Comment by anselal** [comment]
Nicely done. Now the requirements file is up to date.

**Comment by atulmishra-one** [comment]
Thank you for reporting.
